---
title: "Tidy Tuesday 44 - Ultra Running"
Author: "Kyle Proctor"
output: "html_notebook"
---
###Running isn’t a word that has ever been in my vocabulary, except in the old days when I might run to the break room when I hear someone brought Krispy Kreme doughnuts to the station. For this week’s Tidy Tuesday, I had to turn to Wikipedia to figure out what exactly “ultra running” is and how it differs from regular running so I could understand the data I’m working with a bit better.<br><br>
###After looking into ultra running and the data that was offered, I instantly took to the nationality section. Having a history in Model United Nations and Model Arab League, I was interested to see what countries participated and where they participated at. However, at this point, I’m slightly limited in knowledge to be able to tell the data stories that I’m looking for, so I’m keeping it basic, but I did learn some new tricks this week!<br><br>
###It came as not much of a surprise that the United States came in first place, but I was intrigued to see how the rest of the top 10 would populate out. It was interesting which nations appeared as four of the seven continents had representation in North America, Europe, Asia, and Australia. South America, Africa, and Antarctica were the only ones without representation.<br><br>
###Want to take part in #TidyTuesday? Get more info over here: https://github.com/rfordatascience/tidytuesday/blob/master/README.md <br><br>
```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)

library(tidyverse)

ultra_rankings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-10-26/ultra_rankings.csv', show_col_types = FALSE)

gt <- ultra_rankings %>% #New data frame with all the data controls
  filter(rank==1) %>% #Only results in showing rows with first place finishes
  group_by(nationality) %>% 
  count(nationality) %>%
  arrange(-n) %>% 
  head(10) #Anything over 15 pops up an NA on that column

#create reference tibble
countries_abr <- c('AFG','ALB','DZA', 	'ASM', 	'AND', 	'AGO', 	'AIA', 	'ATA', 	'ATG', 	'ARG', 	'ARM', 	'ABW', 	'AUS', 	'AUT', 	'AZE', 	'BHS', 	'BHR', 	'BGD', 	'BRB', 	'BLR', 	'BEL', 	'BLZ', 	'BEN', 	'BMU', 	'BTN', 	'BOL', 	'BES', 	'BIH', 	'BWA', 	'BVT', 	'BRA', 	'IOT', 	'BRN', 	'BGR', 	'BFA', 	'BDI', 	'CPV', 	'KHM', 	'CMR', 	'CAN', 	'CYM', 	'CAF', 	'TCD', 	'CHL', 	'CHN', 	'CXR', 	'CCK', 	'COL', 	'COM', 	'COD', 	'COG', 	'COK', 	'CRI', 	'HRV', 	'CUB', 	'CUW', 	'CYP', 	'CZE', 	'CIV', 	'DNK', 	'DJI', 	'DMA', 	'DOM', 	'ECU', 	'EGY', 	'SLV', 	'GNQ', 	'ERI', 	'EST', 	'SWZ', 	'ETH', 	'FLK', 	'FRO', 	'FJI', 	'FIN', 	'FRA', 	'GUF', 	'PYF', 	'ATF', 	'GAB', 	'GMB', 	'GEO', 	'DEU', 	'GHA', 	'GIB', 	'GRC', 	'GRL', 	'GRD', 	'GLP', 	'GUM', 	'GTM', 	'GGY', 	'GIN', 	'GNB', 	'GUY', 	'HTI', 	'HMD', 	'VAT', 	'HND', 	'HKG', 	'HUN', 	'ISL', 	'IND', 	'IDN', 	'IRN', 	'IRQ', 	'IRL', 	'IMN', 	'ISR', 	'ITA', 	'JAM', 	'JPN', 	'JEY', 	'JOR', 	'KAZ', 	'KEN', 	'KIR', 	'PRK', 	'KOR', 	'KWT', 	'KGZ', 	'LAO', 	'LVA', 	'LBN', 	'LSO', 	'LBR', 	'LBY', 	'LIE', 	'LTU', 	'LUX', 	'MAC', 	'MDG', 	'MWI', 	'MYS', 	'MDV', 	'MLI', 	'MLT', 	'MHL', 	'MTQ', 	'MRT', 	'MUS', 	'MYT', 	'MEX', 	'FSM', 	'MDA', 	'MCO', 	'MNG', 	'MNE', 	'MSR', 	'MAR', 	'MOZ', 	'MMR', 	'NAM', 	'NRU', 	'NPL', 	'NLD', 	'NCL', 	'NZL', 	'NIC', 	'NER', 	'NGA', 	'NIU', 	'NFK', 	'MNP', 	'NOR', 	'OMN', 	'PAK', 	'PLW', 	'PSE', 	'PAN', 	'PNG', 	'PRY', 	'PER', 	'PHL', 	'PCN', 	'POL', 	'PRT', 	'PRI', 	'QAT', 	'MKD', 	'ROU', 	'RUS', 	'RWA', 	'REU', 	'BLM', 	'SHN', 	'KNA', 	'LCA', 	'MAF', 	'SPM', 	'VCT', 	'WSM', 	'SMR', 	'STP', 	'SAU', 	'SEN', 	'SRB', 	'SYC', 	'SLE', 	'SGP', 	'SXM', 	'SVK', 	'SVN', 	'SLB', 	'SOM', 	'ZAF', 	'SGS', 	'SSD', 	'ESP', 	'LKA', 	'SDN', 	'SUR', 	'SJM', 	'SWE', 	'CHE', 	'SYR', 	'TWN', 	'TJK', 	'TZA', 	'THA', 	'TLS', 	'TGO', 	'TKL', 	'TON', 	'TTO', 	'TUN', 	'TUR', 	'TKM', 	'TCA', 	'TUV', 	'UGA', 	'UKR', 	'ARE', 	'GBR', 	'UMI', 	'USA', 	'URY', 	'UZB', 	'VUT', 	'VEN', 	'VNM', 	'VGB', 	'VIR', 	'WLF', 	'ESH', 	'YEM', 	'ZMB', 	'ZWE', 	'ALA')
countries_full <- c("Afghanistan",	"Albania",	"Algeria",	"American Samoa",	"Andorra",	"Angola",	"Anguilla",	"Antarctica",	"Antigua and Barbuda",	"Argentina",	"Armenia",	"Aruba",	"Australia",	"Austria",	"Azerbaijan",	"Bahamas",	"Bahrain",	"Bangladesh",	"Barbados",	"Belarus",	"Belgium",	"Belize",	"Benin",	"Bermuda",	"Bhutan",	"Bolivia",	"Bonaire, Sint Eustatius and Saba",	"Bosnia and Herzegovina",	"Botswana",	"Bouvet Island",	"Brazil",	"British Indian Ocean Territory",	"Brunei Darussalam",	"Bulgaria",	"Burkina Faso",	"Burundi",	"Cabo Verde",	"Cambodia",	"Cameroon",	"Canada",	"Cayman Islands",	"Central African Republic",	"Chad",	"Chile",	"China",	"Christmas Island",	"Cocos Islands",	"Colombia",	"Comoros",	"Democratic Republic Congo",	"Congo",	"Cook Islands",	"Costa Rica",	"Croatia",	"Cuba",	"Curaçao",	"Cyprus",	"Czechia",	"Côte d'Ivoire",	"Denmark",	"Djibouti",	"Dominica",	"Dominican Republic",	"Ecuador",	"Egypt",	"El Salvador",	"Equatorial Guinea",	"Eritrea",	"Estonia",	"Eswatini",	"Ethiopia",	"Falkland Islands",	"Faroe Islands",	"Fiji",	"Finland",	"France",	"French Guiana",	"French Polynesia",	"French Southern Territories",	"Gabon",	"Gambia",	"Georgia",	"Germany",	"Ghana",	"Gibraltar",	"Greece",	"Greenland",	"Grenada",	"Guadeloupe",	"Guam",	"Guatemala",	"Guernsey",	"Guinea",	"Guinea-Bissau",	"Guyana",	"Haiti",	"Heard Island and McDonald Islands",	"Holy See ",	"Honduras",	"Hong Kong",	"Hungary",	"Iceland",	"India",	"Indonesia",	"Iran",	"Iraq",	"Ireland",	"Isle of Man",	"Israel",	"Italy",	"Jamaica",	"Japan",	"Jersey",	"Jordan",	"Kazakhstan",	"Kenya",	"Kiribati",	"DPRK",	"Republic of Korea",	"Kuwait",	"Kyrgyzstan",	"Lao People's Democratic Republic",	"Latvia",	"Lebanon",	"Lesotho",	"Liberia",	"Libya",	"Liechtenstein",	"Lithuania",	"Luxembourg",	"Macao",	"Madagascar",	"Malawi",	"Malaysia",	"Maldives",	"Mali",	"Malta",	"Marshall Islands",	"Martinique",	"Mauritania",	"Mauritius",	"Mayotte",	"Mexico",	"Micronesia",	"Moldova",	"Monaco",	"Mongolia",	"Montenegro",	"Montserrat",	"Morocco",	"Mozambique",	"Myanmar",	"Namibia",	"Nauru",	"Nepal",	"Netherlands",	"New Caledonia",	"New Zealand",	"Nicaragua",	"Niger",	"Nigeria",	"Niue",	"Norfolk Island",	"Northern Mariana Islands",	"Norway",	"Oman",	"Pakistan",	"Palau",	"Palestine, State of",	"Panama",	"Papua New Guinea",	"Paraguay",	"Peru",	"Philippines",	"Pitcairn",	"Poland",	"Portugal",	"Puerto Rico",	"Qatar",	"Republic of North Macedonia",	"Romania",	"Russian Federation",	"Rwanda",	"Réunion",	"Saint Barthélemy",	"Saint Helena, Ascension and Tristan da Cunha",	"Saint Kitts and Nevis",	"Saint Lucia",	"Saint Martin",	"Saint Pierre and Miquelon",	"Saint Vincent and the Grenadines",	"Samoa",	"San Marino",	"Sao Tome and Principe",	"Saudi Arabia",	"Senegal",	"Serbia",	"Seychelles",	"Sierra Leone",	"Singapore",	"Sint Maarten",	"Slovakia",	"Slovenia",	"Solomon Islands",	"Somalia",	"South Africa",	"South Georgia and the South Sandwich Islands",	"South Sudan",	"Spain",	"Sri Lanka",	"Sudan",	"Suriname",	"Svalbard and Jan Mayen",	"Sweden",	"Switzerland",	"Syrian Arab Republic",	"Taiwan",	"Tajikistan",	"Tanzania, United Republic of",	"Thailand",	"Timor-Leste",	"Togo",	"Tokelau",	"Tonga",	"Trinidad and Tobago",	"Tunisia",	"Turkey",	"Turkmenistan",	"Turks and Caicos Islands",	"Tuvalu",	"Uganda",	"Ukraine",	"United Arab Emirates",	"United Kingdom",	"United States Minor Outlying Islands",	"United States",	"Uruguay",	"Uzbekistan",	"Vanuatu",	"Venezuela",	"Viet Nam",	"British Virgin Islands ",	"U.S. Virgin Islands",	"Wallis and Futuna",	"Western Sahara",	"Yemen",	"Zambia",	"Zimbabwe",	"Åland Islands")
countries <- tibble(countries_full, countries_abr)

#plot
gt %>% left_join(countries, by = c("nationality" = "countries_abr")) %>% 
  ggplot(aes(x=fct_reorder(countries_full, desc(n)), y=n))+
  geom_bar(stat = "identity", fill="#000000")+
  geom_text(aes(label = n), vjust = -0.5, size = 3)+
  scale_y_continuous(breaks = seq(0,425,25))+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))+ #Axis controls
  
labs(      #Plot Axis and Titles
      title = "Ultra Running First Place Finishes by Nationality", 
      caption = "Data from runrepeat.com", 
      y = "Total First Place Finishes", 
      x = "Runner Nationalities",
    )+
  
theme( #Plot Axis and 
  plot.title = element_text(hjust = 0.5),
  axis.title = element_text(hjust = 0.5)
      )

#Shoutout to the folks at StackOverflow and R Studio that helped with my questions as I continue learning!
#Country codes from: https://www.iban.com/country-codes 
```

